name: human-view-synthesis-env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.1
    - attrs==21.2.0
    - black==21.12b0
    - cachetools==4.2.4
    - charset-normalizer==2.0.9
    - click==8.0.3
    - decorator==4.4.2
    - fairscale==0.4.4
    - ffmpeg-python==0.2.0
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - 'git+https://github.com/Infinidat/munch'
    - 'git+https://github.com/katsura-jp/pytorch-cosine-annealing-with-warmup'
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - idna==3.3
    - imageio==2.13.3
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.8.2
    - lmdb==1.2.1
    - markdown==3.3.6
    - moviepy==1.0.3
    - multidict==5.2.0
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - oauthlib==3.1.1
    - opencv-python==4.5.4.60
    - packaging==21.3
    - pathspec==0.9.0
    - platformdirs==2.4.0
    - proglog==0.1.9
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==3.0.6
    - pytorch-lightning==1.5.1
    - pywavelets==1.2.0
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-image==0.19.0
    - scipy==1.7.3
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tifffile==2021.11.2
    - tomli==1.2.2
    - torchmetrics==0.6.1
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - yarl==1.7.2
    - zipp==3.6.0
